spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect # disable clob warning
    properties: # disable clob warning
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-230-106-126.compute-1.amazonaws.com:5432/d1qh5bn375qvc8?sslmode=require
    username: xkcyfffauwitmu
    password: 6a6c11f6316af242ca8a25872c8931245d6c645c2a00da1b9335a9f564dfa338

logging:
  level:
    com.coyoapp.tinytask: DEBUG
